# .github/workflows/test.yml

name: test
permissions: {} # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token#defining-access-for-the-github_token-permissions
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # tag=v5.0.0
      - name: Set up Python 3.x
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # tag=v6.0.0
        with:
          python-version: "3.13"
          architecture: "x64"
      - run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install pytest pytest-asyncio
          pip install -e .
          pytest tests/smoke_test_acms.py -v
